### ISSUE TITLE
Messages of n2n-v2's supernode is too much !

### ISSUE THREAD

**Issue by lucktu** [meyerd/n2n#30]
When supernode v2.1 is running (no edgenode): supernode -l 10088 -v -f 1>> /v2.txt   
then a message every minute
`04/Jan/2018 21:44:09 [      n2n.c: 303] Purging old registrations
04/Jan/2018 21:44:09 [      n2n.c: 308] Remove 0 registrations`

When supernode v2.1 is running (no edgenode):supernode -l 10088 -f 1>> /v2.txt   
then nothing, even if edgenode is coming.

In addition, when I go to ssh, run ps, and see (edge is running):
`edge -d abc -a 10.0.0.100 -c n2n -k n2n -l X.X.X:10088`
It's too long, suggest:
`edge`

Thanks a lot!

**Comment by meyerd** [comment]
For the first problem: you have `-v`, which means verbose mode, switched on. This is the intended behavior.
For the second problem: This is with every executable on linux. You will always see the command line arguments in the process list. Because of this reason, there is the possibility to specify the encryption key via an environment variable.

**Comment by lucktu** [comment]
@meyerd 
But not -v for v2, nothing!
