### ISSUE TITLE
Merge this fork in n2n

### ISSUE THREAD

**Issue by lucaderi** [meyerd/n2n#40]
Hi @meyerd I appreciate your work but i would like to merge your repo into n2n. i can give you write access to it if you want, so that we can keep all files in one place and thus better serve the community. Please let me know your thoughts.

**Comment by meyerd** [comment]
Hi, I think merging would be great since - as you see by the delayed answer - have not much resources for maintaining this repo in the way it would deserve.

**Comment by lucaderi** [comment]
Ok so how can we move forward to do that? What are your suggestions?

**Comment by emanuele-f** [comment]
@meyerd please check out https://github.com/ntop/n2n . We are pushing development and we would like to join the forces together

**Comment by meyerd** [comment]
Hi all, sorry for the delays. I definitely would like to port back the changes from here to the ntop repo as the main repo for n2n but as you see I also haven't been able to dedicate much time to the project. I hope to be able to free some time this or next weekend looking into porting the stuff back to the ntop repo by maybe producing some patches or pull requests for certain things I might be able to identify as distinct features. 

Do you have any preferences on what main changes you would like to have ported back or let's pose the question the other way around. What changes would you hesitate to merge into the new mainline?

**Comment by emanuele-f** [comment]
Thank you for your effort. I ask your help to create a list of important changes (commits or more general topics) to backport to the ntop branch. You've been active in the past years so you have a broad view of the most important changes. Once we have clear what to backport, doing it will not be a problem and this is something I or other users can do. I would possibly try preserving the original author of the commits, but I doubt this will be possible.

Some interesting feature from what I've seen:
  - The new new_protocol and p2p_crypto branches, they introduce many changes, I need to spend more time on this but I would avoid backporting gnutls stuff. I would stick with openssl as I think this is pretty standard and easily available on Windows too
  - Some commits introduced hash tables to handle the peers list. Maybe a simpler library like uthash could be used
  - Some users in the ntop branch report that this brach has a better stability to work across multiple OS and there is an higher probability for direct connection between edges. Please see https://github.com/ntop/n2n/issues/93 .
  - Backport the statistics about peers communication: https://github.com/meyerd/n2n/commit/d706d80938cb3afa7f9f47e2729167c5cac19ed1
  - After major features have been backported, I would backport small fixes like https://github.com/meyerd/n2n/commit/a594e4e1e92fc196a01198c003166e34a02e7518

**Comment by emanuele-f** [comment]
I have created a clean diff of the changes of this repo since the first commit, I will begin to manually backport the changes from https://github.com/emanuele-f/n2n/blob/backport/meyerd_diff.diff

**Comment by meyerd** [comment]
Just saw you already did a lot of porting form the master of this repository. I would advise against trying to port the new_protocol and p2p_crypto branches as they mainly contain unfinished work and would take them as an inspiration as to what could be done in a redesign of the protocol. Also some work has been already done in trying to implement but this is far from being finished.

**Comment by emanuele-f** [comment]
This is what I have *not* backported:
- sglist, we will implement this using uthash
- list of peers via management socket, maybe will do this in future
- SCM for windows, the code was mixed with unix, a better way should be found
- The two branches for the reasons above
- The local IP handling

The last point is however crucial. I've seen that the new `n2n_query_peer` message in your branch is now the only carrier for the public IP address of a peer, it also carries the private IP of the peer to solve a behind-same-nat issue. First of all I think that removing the socket information from the n2n_register message is not a good idea, carrying local ip is also a bad idea, and also there are problems with our implementation where we have implemented local peers discovery via mdns. So this part is giving me many toughts, in particular because the registration process is not very clear in the n2n code in general

**Comment by emanuele-f** [comment]
Just an update: ntop/N2N is now robust for P2P connections. What remains to be ported from this branch:

- Remove some redundant information of some message types (e.g. remote peer IP) to reduce header size (this will be done after https://github.com/ntop/n2n/milestone/1 because compatibility will be broken)
- Possibly integrate the `MSG_TYPE_PEER_INFO`

**Comment by emanuele-f** [comment]
Update: MSG_TYPE_PEER_INFO integrated as part of https://github.com/ntop/n2n/commit/f36814b152f3a8d6a47e94f3735df507e52147a4 . I think that all the required integration has been performed, so for me this can be closed.

**Comment by meyerd** [comment]
the actively maintained version of n2n can be found at: https://github.com/ntop/n2n
